### ISSUE TITLE
What about CKEditor ingratiation

### ISSUE THREAD

**Issue by johnef** [armin-abbasi/filemanager#1]
What about CKEditor ingratiation?

**Comment by armin-abbasi** [comment]
Can you be more specific about your issue?!

**Comment by johnef** [comment]
How can I use this Packages with CKEditor as manage and select images and insert them into text area.

**Comment by armin-abbasi** [comment]
This package is not integrated with CKEditor, I think you should look somewhere else for such a thing! ;)
